services:
  postgres:
    image: postgres:16
    container_name: pragma_postgres
    environment:
      POSTGRES_DB: pragma
      POSTGRES_USER: pragma
      POSTGRES_PASSWORD: pragma
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: